from continuumio/miniconda3

workdir /home

copy pangeo_libs.yml /home


run conda config --add channels conda-forge --force && \
    conda install -y mamba && \
    mamba env update -n base --file pangeo_libs.yml
